services:
  shrinevtt:
    container_name: shrinevtt
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"

    volumes:
      - data:/app/data

    environment:
      NODE_ENV: "production"
      DATA_DIR: "/app/data"
      JWT_SECRET: "dev-only-change-me"
      GM_PASSWORD: "123456"
      PORT: "8080"

volumes:
  data:
