services:
  shrinevtt:
    build: .
    ports:
      - "4173:4173"
    restart: unless-stopped

  shrine_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./.env.example:/app/.env:ro
    restart: unless-stopped

  discord_bridge:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: [ "node", "server/discord_bridge.js" ]
    depends_on:
      - shrine_server
    env_file: .env.example
    restart: unless-stopped
