version: "3.9"

services:
  shrinevtt:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - shrinevtt-data:/app/data
    restart: unless-stopped

volumes:
  shrinevtt-data:
